(defun alist->ht (alist)
  (let ((ht (make-hash-table)))
    (mapcar #'(lambda (c)
		(setf (gethash (car c) ht)
		      (cdr c)))
	    alist)
    ht))

(defun ht->alist (ht)
  (let ((alist nil))
    (maphash #'(lambda (k v)
		 (push (cons k v) alist))
	     ht)
    alist))